use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Creates a minimal `home.nix` in `dir` if one doesn't already exist,
/// importing `nixbox-packages.nix` alongside it.
pub fn ensure_home_nix(dir: &Path) -> Result<()> {
    let home_nix = dir.join("home.nix");
    if home_nix.exists() {
        return Ok(());
    }
    fs::create_dir_all(dir)
        .with_context(|| format!("creating {}", dir.display()))?;
    let username = std::env::var("USER").unwrap_or_else(|_| "user".into());
    let home_dir = std::env::var("HOME").unwrap_or_else(|_| format!("/home/{username}"));
    let content = format!(
        "# Generated by nixbox. Feel free to extend this file.\n\
         {{ config, pkgs, ... }}:\n\
         {{\n\
         \x20 imports = [ ./nixbox-home-packages.nix ];\n\n\
         \x20 home.username = \"{username}\";\n\
         \x20 home.homeDirectory = \"{home_dir}\";\n\n\
         \x20 # Keep this in sync with your nixpkgs channel.\n\
         \x20 home.stateVersion = \"24.11\";\n\
         \x20 programs.home-manager.enable = true;\n\
         }}\n"
    );
    fs::write(&home_nix, content)
        .with_context(|| format!("writing {}", home_nix.display()))?;
    Ok(())
}

const MANIFEST_HEADER: &str = "# Managed by nixbox. Do not edit by hand.";

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Manifest {
    pub packages: BTreeSet<String>,
}

impl Manifest {
    pub fn add(&mut self, pname: &str) -> bool {
        self.packages.insert(pname.to_string())
    }

    pub fn remove(&mut self, pname: &str) -> bool {
        self.packages.remove(pname)
    }
}

pub struct ManagedFile {
    path: PathBuf,
}

impl ManagedFile {
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into() }
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn load(&self) -> Result<Manifest> {
        if !self.path.exists() {
            return Ok(Manifest::default());
        }
        let raw = fs::read_to_string(&self.path)
            .with_context(|| format!("reading {}", self.path.display()))?;
        Ok(parse(&raw))
    }

    pub fn write_home_manager(&self, manifest: &Manifest) -> Result<()> {
        self.write(render_home_manager(manifest))
    }

    pub fn write_nixos(&self, manifest: &Manifest) -> Result<()> {
        self.write(render_nixos(manifest))
    }

    fn write(&self, content: String) -> Result<()> {
        if let Some(parent) = self.path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        fs::write(&self.path, content)
            .with_context(|| format!("writing {}", self.path.display()))
    }
}

fn parse(raw: &str) -> Manifest {
    let mut packages = BTreeSet::new();
    let mut in_block = false;
    for line in raw.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("# nixbox:packages:start") {
            in_block = true;
            continue;
        }
        if trimmed.starts_with("# nixbox:packages:end") {
            in_block = false;
            continue;
        }
        if in_block && !trimmed.is_empty() && !trimmed.starts_with('#') {
            let token = trimmed.trim_end_matches(';');
            if let Some(pname) = token.strip_prefix("pkgs.") {
                packages.insert(pname.to_string());
            }
        }
    }
    Manifest { packages }
}

fn render_packages(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("    # nixbox:packages:start\n");
    for pname in &manifest.packages {
        out.push_str(&format!("    pkgs.{}\n", pname));
    }
    out.push_str("    # nixbox:packages:end\n");
    out
}

fn render_home_manager(manifest: &Manifest) -> String {
    format!(
        "{header}\n{{ pkgs, ... }}:\n{{\n  home.packages = [\n{body}  ];\n}}\n",
        header = MANIFEST_HEADER,
        body = render_packages(manifest),
    )
}

fn render_nixos(manifest: &Manifest) -> String {
    format!(
        "{header}\n{{ pkgs, ... }}:\n{{\n  environment.systemPackages = [\n{body}  ];\n}}\n",
        header = MANIFEST_HEADER,
        body = render_packages(manifest),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_home_manager() {
        let mut m = Manifest::default();
        m.add("ripgrep");
        m.add("fd");
        let rendered = render_home_manager(&m);
        let parsed = parse(&rendered);
        assert_eq!(parsed.packages, m.packages);
    }

    #[test]
    fn round_trip_nixos() {
        let mut m = Manifest::default();
        m.add("htop");
        let rendered = render_nixos(&m);
        let parsed = parse(&rendered);
        assert_eq!(parsed.packages, m.packages);
    }
}
